import React from 'react';
import ReactDOM from 'react-dom/client';
import App from './App.jsx';
import './index.css';
import { Amplify } from 'aws-amplify';
import config from '../amplify_outputs.json';  // Generated by sandbox
import { Authenticator } from '@aws-amplify/ui-react';
import '@aws-amplify/ui-react/styles.css';  // Import styles

Amplify.configure(config);

ReactDOM.createRoot(document.getElementById('root')).render(
  <React.StrictMode>
    <Authenticator>  {/* Wraps app with auth UI */}
      <App />
    </Authenticator>
  </React.StrictMode>
);